version: '3'
services:

  nginx:
    restart: always
    image: nginx:1.13-alpine
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/lib/pleroma/nginx/static:/usr/share/nginx/html
      - /var/lib/pleroma/uploads:/usr/share/nginx/uploads/media
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
